// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BaseArchitect.Entities
{
    public partial class Course
    {
        public int CourseID { get; set; }
        public string Name { get; set; }
        public long Price { get; set; }
        public int? CourseCategoryID { get; set; }
        public string Description { get; set; }
        public int? Type { get; set; }
        public bool? GrantCertificate { get; set; }
        public int? Sale { get; set; }
        public int? TeacherID { get; set; }
        public int? Rating { get; set; }
        public int? QuantiyRate { get; set; }
        public DateTime? TimeStart { get; set; }
        public DateTime? TimeEnd { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool Deleted { get; set; }
        public Guid? Code { get; set; }
    }
}