// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BaseArchitect.Entities
{
    public partial class RefreshToken
    {
        public int RefreshTokenID { get; set; }
        public string ReToken { get; set; }
        public DateTime ExpiredDate { get; set; }
        public int AccountID { get; set; }
    }
}