// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BaseArchitect.Entities
{
    public partial class V_Account
    {
        public int AccountID { get; set; }
        public string Name { get; set; }
        public string RoleName { get; set; }
    }
}